actions: '*'
attn_drop_rate: 0.0
batch_size: 972
checkpoint: checkpoint/ablation_tpm_tri
checkpoint_frequency: 10000
data_augmentation: true
dataset: h36m
depth: 8
drop_path_rate: 0.2
drop_rate: 0.0
embed_dim: 512
epochs: 160
evaluate: ''
hierarchical_layer_indices: 1,2
hierarchical_token_nums: 121,81
keypoints: cpn_ft_h36m_dbb
layer_index: 1
learning_rate: 4.0e-05
lr_decay: 0.99
master_addr: 127.0.0.1
master_port: '8600'
min_loss: 100000
mlp_ratio: 2.0
model: h2ot_mixste_interp
nolog: false
num_heads: 8
num_joints: 17
num_workers: 4
number_of_frames: 243
patch_size: 9
pruning_strategy: motion
recovery_layer_indices: ''
recovery_on_hierarchy: false
recovery_strategy: attention
recovery_token_nums: ''
reduce_rank: 0
resume: ''
subjects_test: S9,S11
subjects_train: S1,S5,S6,S7,S8
subset: 1
token_num: 81
wandb: false
weight_angle: 0.001
weight_bone: 100.0
weight_symmetry: 50.0
world_size: 1
